import type { Metadata } from 'next';
import { Be_Vietnam_Pro } from 'next/font/google';
import Header from '@/components/header';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

const beVnPro = Be_Vietnam_Pro({
	weight: ['200', '300', '400', '500', '600', '700'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${beVnPro.className} bg-[#16254D]`}>
				<Header />
				{children}
				<ToastContainer />
			</body>
		</html>
	);
}
